### ISSUE TITLE
Error deploying documents

### ISSUE THREAD

**Issue by lteacher** [kevinohara80/dmc#28]
Hello,

I have noticed there is an issue with deploying folders under documents. It would seem that the check to determine if the file should have the `-meta.xml` does not consider that there may be nested folders in there?
![image](https://cloud.githubusercontent.com/assets/6103860/14624254/75c31c32-061c-11e6-9e69-a8b205311405.png)

**Comment by lessonteacher** [comment]
Essentially it seems that at [parseFilePath()][01] there is a part where it [gets the type from the folder][02] which is `documents` but in the end the path here is actually to a dir. 

The type now has the `hasMetaXML` as true since its documents. 

Though, looking closely I also noticed that there is another check in the [getFilePaths()][03] function which gets from the type, during iteration. This check actually seems erroneous but complicates the issue I guess because from `Document` metaType it isnt as helpful vs being able to use the file path. I was thinking as a suggestion that you could check the extension using `path` or something.

[01]:https://github.com/kevinohara80/dmc/blob/master/lib/index.js#L136
[02]:https://github.com/kevinohara80/dmc/blob/master/lib/index.js#L155
[03]:https://github.com/kevinohara80/dmc/blob/master/lib/metadata-map.js#L201

**Comment by kevinohara80** [comment]
Yeah, the subfoldered metadata needs some work. For now doing `dmc deploy src/documents/images/*` should work.

**Comment by lessonteacher** [comment]
Actually, in review its kind of an outcome of the glob. I tested the above and found that the folders probably don't even belong in the list, but since the glob is something like `src/documents/**/*` they are picked up. 

I'm not sure if there are other valid cases where folders would be added? I assume not since when i messed around above I saw that they get put into the `package.xml` later which then fails.

So finally perhaps, the best is to just not allow dirs?
[01]:https://github.com/kevinohara80/dmc/blob/master/lib/get-files.js#L27
